name: Check bundle size diff (pure)

on:
  pull_request:

jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Upload stats.pure.json
      uses: actions/upload-artifact@v1
      with:
        name: head-stats
        path: ./build/stats.pure.json
  build-base:
    name: 'Build base'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ## Here we do not checkout the current branch, but we checkout the base branch.
        ref: ${{ github.base_ref }}
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Upload stats.pure.json
      uses: actions/upload-artifact@v1
      with:
        name: base-stats
        path: ./build/stats.pure.json
  compare:
    name: 'Compare base & head bundle sizes'
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    steps:
    - uses: actions/checkout@v1
    - name: Download base artifact
      uses: actions/download-artifact@v1
      with:
        name: base-stats
    - name: Download head artifact
      uses: actions/download-artifact@v1
      with:
        name: head-stats
    - name: Diff between base & head
      uses: chronotruck/webpack-stats-diff-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base_stats_path: ./base-stats/stats.pure.json
        head_stats_path: ./head-stats/stats.pure.json
